version: "3"

services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  pwcrack-frontend:
    container_name: pwcrack-frontend
    image: node:lts
    hostname: pwcrack-frontend
    ports:
      - 4200:4200
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: bash -c 'yarn install && yarn start --host 0.0.0.0'

  riddler-backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: pwcrack-backend
    hostname: pwcrack-backend
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - MONGO_CONN_STRING=mongodb://root:password@mongo:27017/pwcrack?authSource=admin
      - JTR_ROOT=/opt/jtr/
      - JTR_EXECUTABLE=/opt/jtr/JohnTheRipper/run/john
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: bash -c 'yarn install && yarn start:dev'
