version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
  - package_manager: "javascript"
    directory: "/backend"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
